baseurl: "https://example.org/"
languageCode: "en-us"
title: "Hugo CI/CD Example"
theme: "hugo-xmin"
footnotereturnlinkcontents: "â†©"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Posts
      url: "posts/"
      weight: 2

params:
  description: ""
  footer: ""