baseurl: "https://example.org/"
languageCode: "en-us"
title: "Hugo CI/CD Example"
theme: "hugo-xmin"
footnotereturnlinkcontents: "â†©"

menu:
  main:
    - name: Posts
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2

params:
  description: "more description: [...]"
  footer: "footer content"